### PR TITLE
Fix the wlan1(ap) interface create failed issue

### PR DESCRIPTION
**Pull request by zhaoye1**
add wifi_virtual_interface_create function, return success

### CODE REVIEW

**Comment by zhaoye1** [comment]
@balajim001  please help me review the patch, and help me add Panda, Bharat B to review, thanks.

**Comment by zhaoye1** [comment]
@bpanda24 please help me review the patch

**Comment by zhaoye1** [comment]
@bpanda24 please help me review the patch

**Review by bpanda24 — APPROVED** [review]

**Review by maozhong1 — APPROVED** [review]

**Review by lchen43 — APPROVED** [review]
LGTM

**Review by dyang23 — APPROVED** [review]
LGTM

**Pull request merged**
